---
Name: silverware-twitter
---

# Configure Content Controller:

SilverStripe\CMS\Controllers\ContentController:
  required_js:
    - silverware-twitter/client/dist/js/bundle.js

# Configure Site Configuration:

SilverStripe\SiteConfig\SiteConfig:
  twitter_languages:
    en: English
    ar: Arabic
    bn: Bengali
    cs: Czech
    da: Danish
    de: German
    el: Greek
    es: Spanish
    fa: Persian
    fi: Finnish
    fil: Filipino
    fr: French
    he: Hebrew
    hi: Hindi
    hu: Hungarian
    id: Indonesian
    it: Italian
    ja: Japanese
    ko: Korean
    msa: Malay
    nl: Dutch
    no: Norwegian
    pl: Polish
    pt: Portuguese
    ro: Romanian
    ru: Russian
    sv: Swedish
    th: Thai
    tr: Turkish
    uk: Ukrainian
    ur: Urdu
    vi: Vietnamese
    zh-cn: Chinese (Simplified)
    zh-tw: Chinese (Traditional)
